"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 14:35:54.346328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_imports',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('file_name', sa.String(length=240), nullable=False),
    sa.Column('data_section', sa.String(length=60), nullable=False),
    sa.Column('column_headers', sa.JSON(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sop_templates',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('min_rule', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name=op.f('uq_sop_templates_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditor_availability',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('auditor_id', sa.String(length=12), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('process', sa.String(length=80), nullable=True),
    sa.Column('sub_process', sa.String(length=120), nullable=True),
    sa.Column('audit_type', sa.String(length=60), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('photo_video_enablement', sa.String(length=10), nullable=True),
    sa.Column('data_analyst_enabled', sa.String(length=10), nullable=True),
    sa.Column('data_analyst_reference', sa.String(length=60), nullable=True),
    sa.Column('annex', sa.String(length=120), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('proposed_by_id', sa.String(length=12), nullable=True),
    sa.Column('approved_by_id', sa.String(length=12), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_code'), ['code'], unique=False)

    op.create_table('sop_sections',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('template_id', sa.String(length=12), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['sop_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sop_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_sections_template_id'), ['template_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('store_format', sa.String(length=20), nullable=True),
    sa.Column('store_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('manager_id', sa.String(length=12), nullable=True),
    sa.Column('contact', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('store_code', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('deputy_manager', sa.String(length=120), nullable=True),
    sa.Column('operations_manager', sa.String(length=120), nullable=True),
    sa.Column('store_category', sa.String(length=80), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_store_code'), ['store_code'], unique=False)

    op.create_table('audits',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('store_id', sa.String(length=20), nullable=False),
    sa.Column('checklist_id', sa.String(length=12), nullable=True),
    sa.Column('auditor_id', sa.String(length=12), nullable=True),
    sa.Column('created_by_id', sa.String(length=12), nullable=True),
    sa.Column('audit_type', sa.String(length=60), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('approved_by_id', sa.String(length=12), nullable=True),
    sa.Column('sm_rating', sa.Integer(), nullable=True),
    sa.Column('sm_comment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_deposit_pickups',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('import_id', sa.String(length=12), nullable=True),
    sa.Column('store_id', sa.String(length=20), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('sales_date', sa.Date(), nullable=True),
    sa.Column('cash_sales', sa.Float(), nullable=True),
    sa.Column('cash_deposited', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('cms_pickup_date', sa.Date(), nullable=True),
    sa.Column('handover_delay_days', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['data_imports.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_deposit_pickups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_deposit_pickups_store_id'), ['store_id'], unique=False)

    op.create_table('cash_reconciliations',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('import_id', sa.String(length=12), nullable=True),
    sa.Column('store_id', sa.String(length=20), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('cash_at_tills', sa.Float(), nullable=True),
    sa.Column('cash_in_safe', sa.Float(), nullable=True),
    sa.Column('cash_other_locations', sa.Float(), nullable=True),
    sa.Column('physical_cash_total', sa.Float(), nullable=True),
    sa.Column('cash_sales_as_per_report', sa.Float(), nullable=True),
    sa.Column('float_or_imprest_amount', sa.Float(), nullable=True),
    sa.Column('book_cash_total', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['data_imports.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_reconciliations_store_id'), ['store_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('checklist_id', sa.String(length=12), nullable=True),
    sa.Column('question_id', sa.String(length=12), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expired_inventory',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('import_id', sa.String(length=12), nullable=True),
    sa.Column('store_id', sa.String(length=20), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('article_code', sa.String(length=80), nullable=True),
    sa.Column('article_description', sa.String(length=240), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['data_imports.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expired_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expired_inventory_article_code'), ['article_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_expired_inventory_store_id'), ['store_id'], unique=False)

    op.create_table('sop_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=12), nullable=False),
    sa.Column('store_id', sa.String(length=20), nullable=False),
    sa.Column('auditor_id', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('overall_remarks', sa.Text(), nullable=True),
    sa.Column('client_created_at', sa.DateTime(), nullable=True),
    sa.Column('client_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['sop_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sop_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_audits_auditor_id'), ['auditor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sop_audits_store_id'), ['store_id'], unique=False)

    op.create_table('sop_criteria',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('section_id', sa.String(length=12), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('max_text', sa.Text(), nullable=True),
    sa.Column('avg_text', sa.Text(), nullable=True),
    sa.Column('min_text', sa.Text(), nullable=True),
    sa.Column('min_points', sa.Float(), nullable=True),
    sa.Column('default_na', sa.Boolean(), nullable=True),
    sa.Column('requires_comment', sa.Boolean(), nullable=True),
    sa.Column('requires_photo', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sop_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sop_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_criteria_section_id'), ['section_id'], unique=False)

    op.create_table('store_scores',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('import_id', sa.String(length=12), nullable=True),
    sa.Column('store_id', sa.String(length=20), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('store_code', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('q1', sa.Float(), nullable=True),
    sa.Column('q2', sa.Float(), nullable=True),
    sa.Column('q3', sa.Float(), nullable=True),
    sa.Column('q4', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['data_imports.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_scores_store_code'), ['store_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_scores_store_id'), ['store_id'], unique=False)

    op.create_table('audit_responses',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('audit_id', sa.String(length=20), nullable=True),
    sa.Column('question_id', sa.String(length=12), nullable=True),
    sa.Column('answer', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('audit_id', sa.String(length=20), nullable=True),
    sa.Column('store_id', sa.String(length=20), nullable=True),
    sa.Column('sr_no', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('person_responsible', sa.String(length=160), nullable=True),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_store_id'), ['store_id'], unique=False)

    op.create_table('sop_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=True),
    sa.Column('criterion_id', sa.String(length=12), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=60), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['sop_audits.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['sop_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sop_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_attachments_audit_id'), ['audit_id'], unique=False)

    op.create_table('sop_audit_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=True),
    sa.Column('criterion_id', sa.String(length=12), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_na', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['sop_audits.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['sop_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sop_audit_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_audit_scores_audit_id'), ['audit_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('audit_id', sa.String(length=20), nullable=True),
    sa.Column('store_id', sa.String(length=20), nullable=True),
    sa.Column('response_id', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process', sa.String(length=80), nullable=True),
    sa.Column('sub_process', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assignee_id', sa.String(length=12), nullable=True),
    sa.Column('raised_by_id', sa.String(length=12), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['audit_responses.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    with op.batch_alter_table('sop_audit_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_audit_scores_audit_id'))

    op.drop_table('sop_audit_scores')
    with op.batch_alter_table('sop_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_attachments_audit_id'))

    op.drop_table('sop_attachments')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_store_id'))
        batch_op.drop_index(batch_op.f('ix_observations_audit_id'))

    op.drop_table('observations')
    op.drop_table('audit_responses')
    with op.batch_alter_table('store_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_scores_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_scores_store_code'))

    op.drop_table('store_scores')
    with op.batch_alter_table('sop_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_criteria_section_id'))

    op.drop_table('sop_criteria')
    with op.batch_alter_table('sop_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_audits_store_id'))
        batch_op.drop_index(batch_op.f('ix_sop_audits_auditor_id'))

    op.drop_table('sop_audits')
    with op.batch_alter_table('expired_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expired_inventory_store_id'))
        batch_op.drop_index(batch_op.f('ix_expired_inventory_article_code'))

    op.drop_table('expired_inventory')
    op.drop_table('checklist_items')
    with op.batch_alter_table('cash_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_reconciliations_store_id'))

    op.drop_table('cash_reconciliations')
    with op.batch_alter_table('cash_deposit_pickups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_deposit_pickups_store_id'))

    op.drop_table('cash_deposit_pickups')
    op.drop_table('audits')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_store_code'))

    op.drop_table('stores')
    with op.batch_alter_table('sop_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_sections_template_id'))

    op.drop_table('sop_sections')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_code'))

    op.drop_table('questions')
    op.drop_table('auditor_availability')
    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sop_templates')
    op.drop_table('data_imports')
    op.drop_table('checklists')
    # ### end Alembic commands ###
